# Generated by Django 5.0 on 2023-12-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinputmodel',
            old_name='size',
            new_name='bhk',
        ),
    ]
